name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: { node-version: 18 }

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - run: npm install

      - run: chmod +x ./android/gradlew

      - run: mkdir -p android/app/src/main/assets

      - name: Bundle JS only (no assets-dest)
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle

      - run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
