name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java and Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            android/.gradle
            ~/.gradle
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install dependencies
        run: yarn install

      - name: Remove deprecated masked-view
        run: yarn remove @react-native-community/masked-view

      - name: Create required assets directory
        run: mkdir -p android/app/src/main/assets

      - name: Bundle JS for Android
        run: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res

      - name: Clean Android build
        run: cd android && ./gradlew clean

      - name: Build release APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
